# Shared properties for PostgreSQL db
postgres: &postgres
  adapter: postgres
  database: rails_blog
  user: postgres
  default_schema: public

# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  <<: *postgres
  default_schema: public

test:
  <<: *postgres
  default_schema: test

production:
  <<: *postgres
  default_schema: production

