---
common: &common
  #license_key: d67afc830dab717fd163bfcb0b8b88423e9a1a3b
  #host: staging-collector.newrelic.com
  #api_host: staging-collector.newrelic.com
  #port: 80
  #ssl: false

  license_key: bootstrap_newrelic_admin_license_key_000
  host: localhost
  #port: 8081
  port: 8888
  ssl: false
 
  enabled: true
  monitor_mode: true

  app_name: kiq
  log_level: debug
  apdex_t: 0.0
  capture_params: false
  transaction_tracer: &70195347551140
    enabled: true
    transaction_threshold: 0.0
    record_sql: obfuscated
    stack_trace_threshold: 0.0
  error_collector: &70195347547740
    enabled: true
    capture_source: true
  #audit_log:
    #enabled: true
development:
  <<: *common
test:
  <<: *common
production:
  <<: *common
staging:
  <<: *common
