#!/usr/bin/env ruby
# This script is only used manually in dev mode
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
#require 'delayed/command'
#Delayed::Command.new(ARGV).daemonize
puts "DJ init..."
Delayed::Worker.new().start
