#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
ENV['rpm_app_name'] = "#{RAILS_ENV.capitalize} DJ"
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize
